CREATE TABLE T_USER (
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50),
    AUTHORITY VARCHAR(50),
    NAME VARCHAR(50),
    COMPANY VARCHAR(50),
	PERMIT varchar(50) DEFAULT 'N',
    PRIMARY KEY (USERNAME)
);

drop table T_EMP_POOL;
--------------------------------------------------------------------------------
CREATE TABLE T_EMP_POOL (
    EMP_POOL_ID SERIAL NOT NULL,
    SOURCING_MANAGER VARCHAR(50),
    NAME VARCHAR(50),
    PHONENUMBER VARCHAR(50),
    BIRTHDATE Date,
    EMAIL VARCHAR(50),
    ADDRESS VARCHAR(200),
    EDUCATION VARCHAR(200),
    SCHOOL_NAME VARCHAR(200),
    MAJOR VARCHAR(200),
    CAREER_YEARS VARCHAR(50),
    CAREER_FIELD VARCHAR(200),
    CAREER_LEVEL VARCHAR(50),
    PROJECT_ASSIGN VARCHAR(50),
	del VARCHAR(50),
    PRIMARY KEY (EMP_POOL_ID)
);
-------------------------------------------------------------------------------- 

CREATE TABLE T_SALES_LEDGER (
    SALES_ID SERIAL NOT NULL,
    EMP_ID INTEGER,
    TECH_SUPPORT CHAR(1),
    EXTRA_EXPENSE VARCHAR(50),
    EXTRA_EXPENSE_AMOUNT NUMERIC,
    JOB_LEVEL VARCHAR(50),
    JOB_ROLE VARCHAR(50),
    JOB_FIELD VARCHAR(50),
    BABY_LEAVE_COMMENTS VARCHAR(200),
    EMP_TYPE VARCHAR(50),
    I_C_CLASS CHAR(1),
    I_C_COMPANY_NAME VARCHAR(200),
    RECENT_AMOUNT_HISTORY VARCHAR(200),
    MODIFIER VARCHAR(50),
	PAYDAY VARCHAR(50),
    PRIMARY KEY (SALES_ID)
);
--------------------------------------------------------------------------------
CREATE TABLE T_CLIENT (-- 거래처테이블
    CLIENT_ID SERIAL NOT NULL,
    SALES_SOURCE VARCHAR(200),
    CLIENT VARCHAR(200),
    SUBCONTRACT VARCHAR(200),
    PROJECT_NAME VARCHAR(200),
    BUSINESS_DEPARTMENT VARCHAR(50),
    BUSINESS_MANAGER VARCHAR(50),
    PRIMARY KEY (CLIENT_ID)
);
--------------------------------------------------------------------------------

CREATE TABLE T_EMP_LEDGER ( --기초인력원장 도환씨
    EMP_ID SERIAL NOT NULL,
    EMP_POOL_ID INTEGER,
    CLIENT_ID INTEGER,
    COMPANY VARCHAR(50),
    ASSIGN_DATE DATE,
    END_DATE DATE,
    SALES_MM NUMERIC(10,3),
    PURCHASE_MM NUMERIC(10,3),
    SALES_UNIT INTEGER,
    PURCHASE_UNIT INTEGER,
    COMMENTS VARCHAR(200),
    RESUME_SUBMIT_DATE DATE,
    RESIGN_DATE DATE,
    I_CONTRACT_DATE DATE,
    C_CONTRACT_DATE DATE,
    PROGRESS VARCHAR(200),
    PROGRESS_REASON VARCHAR(200),
    RESULT VARCHAR(200),
    RESULT_REASON VARCHAR(200),
    ISSUES VARCHAR(200),
    PRIMARY KEY (EMP_ID),
    CONSTRAINT T_E_L_FK_EMP_POOL_ID FOREIGN KEY (EMP_POOL_ID) REFERENCES T_EMP_POOL (EMP_POOL_ID),
    CONSTRAINT T_E_L_FK_CLIENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES T_CLIENT (CLIENT_ID)
);
--------------------------------------------------------------------------------  2023.03.24

CREATE TABLE T_EMP_RESUME (
    RESUME_ID SERIAL NOT NULL,
    EMP_POOL_ID INTEGER,
    NAME VARCHAR(50),
    PHONENUMBER VARCHAR(50),
    FILE_NAME VARCHAR(200),
    FILE_REGDATE DATE,
    PRIMARY KEY (RESUME_ID),
    CONSTRAINT T_E_R_FK_EMP_POOL_ID FOREIGN KEY (EMP_POOL_ID) REFERENCES T_EMP_POOL (EMP_POOL_ID)
);
--------------------------------------------------------------------------------


CREATE TABLE T_MONTH_SALES_LEDGER (
    MONTH_SALES_ID SERIAL NOT NULL,
    SALES_ID INTEGER,
    EMP_ID INTEGER,
    EMP_POOL_ID INTEGER,
    CLIENT_ID INTEGER,
    SALES_YEAR_MONTH DATE,
    INVOICE_INCLUDE CHAR(1),
    PRIMARY KEY (MONTH_SALES_ID),
    CONSTRAINT T_M_S_L_FK_SALES_ID FOREIGN KEY (SALES_ID) REFERENCES T_SALES_LEDGER (SALES_ID),
    CONSTRAINT T_M_S_L_FK_EMP_ID FOREIGN KEY (EMP_ID) REFERENCES T_EMP_LEDGER (EMP_ID),
    CONSTRAINT T_M_S_L_FK_EMP_POOL_ID FOREIGN KEY (EMP_POOL_ID) REFERENCES T_EMP_POOL (EMP_POOL_ID),
    CONSTRAINT T_M_S_L_FK_CLIENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES T_CLIENT (CLIENT_ID)
);
--------------------------------------------------------------------------------
CREATE TABLE T_SALES_ESTIMATION (
    SALES_ESTI_ID SERIAL NOT NULL,
    CLIENT_ID INTEGER,
    INVOICE_PUBLISH_DATE DATE,
    INVOICE_PUBLISH_DATE_COMMENTS VARCHAR(200),
    EXTEND_CONTRACT CHAR(1),
    TOTAL_SALES_AMOUNT NUMERIC(10,2),
    TOTAL_PURCHASE_AMOUNT NUMERIC(10,2),
    COMMENTS VARCHAR(200),
	SALES_ESTI_YEAR_MONTH DATE,
    RETIREMENT_PAY NUMERIC(10,2),
    RESEARCH_PAY NUMERIC(10,2),
    PRIMARY KEY (SALES_ESTI_ID),
    CONSTRAINT T_S_E_FK_CLIENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES T_CLIENT (CLIENT_ID)
);
--------------------------------------------------------------------------------
CREATE TABLE T_SALES_RESULT (
    SALES_RESULT_ID SERIAL NOT NULL,
    CLIENT_ID INTEGER,
    INVOICE_PUBLISH_DATE DATE,
    INVOICE_PUBLISH_DATE_COMMENTS VARCHAR(200),
    EXTEND_CONTRACT CHAR(1),
    TOTAL_SALES_AMOUNT NUMERIC(10,2),
    TOTAL_PURCHASE_AMOUNT NUMERIC(10,2),
    COMMENTS VARCHAR(200),
	SALES_RESULT_YEAR_MONTH DATE,
    RETIREMENT_PAY NUMERIC(10,2),
    RESEARCH_PAY NUMERIC(10,2),
    PRIMARY KEY (SALES_RESULT_ID),
    CONSTRAINT T_S_R_FK_CLIENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES T_CLIENT (CLIENT_ID)
);
